# https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseurl: https://chrisdoingweb.com
title: Chris Doing Web
description: Chris Antes, the Web Developer

languageCode: en-us
defaultContentLanguage: en

theme: beautifulhugo

googleAnalytics: UA-45605370-1

author:
  name: Chris Antes
  email: chris@chrisdoingweb.com
  github: doingweb
  twitter: doingweb
  codepen: doingweb
  linkedin: chrisantes
  stackoverflow: users/467354/doingweb
  reddit: doingweb

permalinks:
  posts: /blog/:year/:slug

enableGitInfo: true

frontmatter:
  lastmod:
    - lastmod
    - date
    - publishDate

params:
  homeTitle: Hi there!
  subtitle: I'm Chris. I'm a software engineer who cheers on his coworkers, can totally help you write those tests, and puts his dishes in the dishwasher.
  logo: images/face.jpg # Expecting square dimensions

  dateFormat: "January 2, 2006"

  mainSections:
    - post

  commit: https://github.com/doingweb/chrisdoingweb.com/tree/
  rss: true
  comments: true
  readingTime: true
  wordCount: true
  socialShare: true
  showRelatedPosts: true

  # Syntax highlighting
  useHLJS: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog
      weight: 2
    - name: About
      url: /about
      weight: 3
